/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactLead {
    id: bigint;
    subject: string;
    name: string;
    createdAt: bigint;
    email: string;
    message: string;
    phone: string;
}
export interface Booking {
    id: bigint;
    status: string;
    serviceCategory: string;
    paymentStatus: PaymentStatus;
    consultantName: string;
    queryDescription: string;
    name: string;
    createdAt: bigint;
    email: string;
    preferredDate: string;
    preferredTime: string;
    phone: string;
    consultationType: ConsultationType;
}
export interface StripeSession {
    status: PaymentStatus;
    bookingId: bigint;
    createdAt: bigint;
    currency: string;
    checkoutUrl: string;
    sessionId: string;
    amount: bigint;
}
export interface Testimonial {
    id: bigint;
    isApproved: boolean;
    name: string;
    createdAt: bigint;
    feedback: string;
    company: string;
    rating?: bigint;
    industry: string;
}
export enum ConsultationType {
    generalGuidance = "generalGuidance",
    serviceSpecific = "serviceSpecific"
}
export enum PaymentStatus {
    na = "na",
    pending = "pending",
    paid = "paid"
}
export interface backendInterface {
    adminApproveTestimonial(id: bigint): Promise<boolean>;
    adminDeleteTestimonial(id: bigint): Promise<boolean>;
    adminGetAllTestimonials(): Promise<Array<Testimonial>>;
    createConsultationCheckout(bookingId: bigint): Promise<string>;
    getApprovedTestimonials(): Promise<Array<Testimonial>>;
    getBookings(): Promise<Array<Booking>>;
    getContactLeads(): Promise<Array<ContactLead>>;
    getPaymentStatus(bookingId: bigint): Promise<PaymentStatus | null>;
    getStripeSession(bookingId: bigint): Promise<StripeSession | null>;
    setAdminPrincipal(newAdmin: string): Promise<void>;
    submitBooking(name: string, email: string, phone: string, serviceCategory: string, preferredDate: string, preferredTime: string, consultantName: string, queryDescription: string): Promise<bigint>;
    submitContactLead(name: string, email: string, phone: string, subject: string, message: string): Promise<bigint>;
    submitGeneralGuidanceBooking(name: string, email: string, phone: string, preferredDate: string, preferredTime: string, queryDescription: string): Promise<bigint>;
    submitTestimonial(name: string, company: string, industry: string, feedback: string, rating: bigint | null): Promise<bigint>;
    updateStripeSession(sessionId: string, paid: boolean): Promise<boolean>;
    verifyConsultationPayment(sessionId: string): Promise<PaymentStatus>;
}
import type { Booking as _Booking, ConsultationType as _ConsultationType, PaymentStatus as _PaymentStatus, StripeSession as _StripeSession, Testimonial as _Testimonial } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminApproveTestimonial(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveTestimonial(arg0);
            return result;
        }
    }
    async adminDeleteTestimonial(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteTestimonial(arg0);
            return result;
        }
    }
    async adminGetAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTestimonials();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTestimonials();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createConsultationCheckout(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createConsultationCheckout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConsultationCheckout(arg0);
            return result;
        }
    }
    async getApprovedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedTestimonials();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedTestimonials();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactLeads(): Promise<Array<ContactLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactLeads();
            return result;
        }
    }
    async getPaymentStatus(arg0: bigint): Promise<PaymentStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentStatus(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentStatus(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSession(arg0: bigint): Promise<StripeSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSession(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSession(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdminPrincipal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPrincipal(arg0);
            return result;
        }
    }
    async submitBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async submitContactLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactLead(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactLead(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitGeneralGuidanceBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGeneralGuidanceBooking(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGeneralGuidanceBooking(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitTestimonial(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0, arg1, arg2, arg3, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0, arg1, arg2, arg3, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateStripeSession(arg0: string, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStripeSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStripeSession(arg0, arg1);
            return result;
        }
    }
    async verifyConsultationPayment(arg0: string): Promise<PaymentStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyConsultationPayment(arg0);
                return from_candid_PaymentStatus_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyConsultationPayment(arg0);
            return from_candid_PaymentStatus_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Booking_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ConsultationType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationType): ConsultationType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSession_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSession): StripeSession {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Testimonial_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Testimonial {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentStatus]): PaymentStatus | null {
    return value.length === 0 ? null : from_candid_PaymentStatus_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StripeSession]): StripeSession | null {
    return value.length === 0 ? null : from_candid_StripeSession_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PaymentStatus;
    bookingId: bigint;
    createdAt: bigint;
    currency: string;
    checkoutUrl: string;
    sessionId: string;
    amount: bigint;
}): {
    status: PaymentStatus;
    bookingId: bigint;
    createdAt: bigint;
    currency: string;
    checkoutUrl: string;
    sessionId: string;
    amount: bigint;
} {
    return {
        status: from_candid_PaymentStatus_n8(_uploadFile, _downloadFile, value.status),
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        currency: value.currency,
        checkoutUrl: value.checkoutUrl,
        sessionId: value.sessionId,
        amount: value.amount
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isApproved: boolean;
    name: string;
    createdAt: bigint;
    feedback: string;
    company: string;
    rating: [] | [bigint];
    industry: string;
}): {
    id: bigint;
    isApproved: boolean;
    name: string;
    createdAt: bigint;
    feedback: string;
    company: string;
    rating?: bigint;
    industry: string;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        name: value.name,
        createdAt: value.createdAt,
        feedback: value.feedback,
        company: value.company,
        rating: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.rating)),
        industry: value.industry
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    serviceCategory: string;
    paymentStatus: _PaymentStatus;
    consultantName: string;
    queryDescription: string;
    name: string;
    createdAt: bigint;
    email: string;
    preferredDate: string;
    preferredTime: string;
    phone: string;
    consultationType: _ConsultationType;
}): {
    id: bigint;
    status: string;
    serviceCategory: string;
    paymentStatus: PaymentStatus;
    consultantName: string;
    queryDescription: string;
    name: string;
    createdAt: bigint;
    email: string;
    preferredDate: string;
    preferredTime: string;
    phone: string;
    consultationType: ConsultationType;
} {
    return {
        id: value.id,
        status: value.status,
        serviceCategory: value.serviceCategory,
        paymentStatus: from_candid_PaymentStatus_n8(_uploadFile, _downloadFile, value.paymentStatus),
        consultantName: value.consultantName,
        queryDescription: value.queryDescription,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        preferredDate: value.preferredDate,
        preferredTime: value.preferredTime,
        phone: value.phone,
        consultationType: from_candid_ConsultationType_n10(_uploadFile, _downloadFile, value.consultationType)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generalGuidance: null;
} | {
    serviceSpecific: null;
}): ConsultationType {
    return "generalGuidance" in value ? ConsultationType.generalGuidance : "serviceSpecific" in value ? ConsultationType.serviceSpecific : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    na: null;
} | {
    pending: null;
} | {
    paid: null;
}): PaymentStatus {
    return "na" in value ? PaymentStatus.na : "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Array<Testimonial> {
    return value.map((x)=>from_candid_Testimonial_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n6(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
