/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : string,
  'serviceCategory' : string,
  'paymentStatus' : PaymentStatus,
  'consultantName' : string,
  'queryDescription' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'preferredDate' : string,
  'preferredTime' : string,
  'phone' : string,
  'consultationType' : ConsultationType,
}
export type ConsultationType = { 'generalGuidance' : null } |
  { 'serviceSpecific' : null };
export interface ContactLead {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type PaymentStatus = { 'na' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface StripeSession {
  'status' : PaymentStatus,
  'bookingId' : bigint,
  'createdAt' : bigint,
  'currency' : string,
  'checkoutUrl' : string,
  'sessionId' : string,
  'amount' : bigint,
}
export interface Testimonial {
  'id' : bigint,
  'isApproved' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'feedback' : string,
  'company' : string,
  'rating' : [] | [bigint],
  'industry' : string,
}
export interface _SERVICE {
  'adminApproveTestimonial' : ActorMethod<[bigint], boolean>,
  'adminDeleteTestimonial' : ActorMethod<[bigint], boolean>,
  'adminGetAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'createConsultationCheckout' : ActorMethod<[bigint], string>,
  'getApprovedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getContactLeads' : ActorMethod<[], Array<ContactLead>>,
  'getPaymentStatus' : ActorMethod<[bigint], [] | [PaymentStatus]>,
  'getStripeSession' : ActorMethod<[bigint], [] | [StripeSession]>,
  'setAdminPrincipal' : ActorMethod<[string], undefined>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    bigint
  >,
  'submitContactLead' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitGeneralGuidanceBooking' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'submitTestimonial' : ActorMethod<
    [string, string, string, string, [] | [bigint]],
    bigint
  >,
  'updateStripeSession' : ActorMethod<[string, boolean], boolean>,
  'verifyConsultationPayment' : ActorMethod<[string], PaymentStatus>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];