/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'feedback' : IDL.Text,
  'company' : IDL.Text,
  'rating' : IDL.Opt(IDL.Nat),
  'industry' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'na' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const ConsultationType = IDL.Variant({
  'generalGuidance' : IDL.Null,
  'serviceSpecific' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'serviceCategory' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'consultantName' : IDL.Text,
  'queryDescription' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
  'consultationType' : ConsultationType,
});
export const ContactLead = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeSession = IDL.Record({
  'status' : PaymentStatus,
  'bookingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'currency' : IDL.Text,
  'checkoutUrl' : IDL.Text,
  'sessionId' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'adminApproveTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminDeleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminGetAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], []),
  'createConsultationCheckout' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getContactLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
  'getPaymentStatus' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentStatus)], ['query']),
  'getStripeSession' : IDL.Func([IDL.Nat], [IDL.Opt(StripeSession)], ['query']),
  'setAdminPrincipal' : IDL.Func([IDL.Text], [], []),
  'submitBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'submitContactLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitGeneralGuidanceBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'updateStripeSession' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'verifyConsultationPayment' : IDL.Func([IDL.Text], [PaymentStatus], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'feedback' : IDL.Text,
    'company' : IDL.Text,
    'rating' : IDL.Opt(IDL.Nat),
    'industry' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'na' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const ConsultationType = IDL.Variant({
    'generalGuidance' : IDL.Null,
    'serviceSpecific' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'serviceCategory' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'consultantName' : IDL.Text,
    'queryDescription' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
    'consultationType' : ConsultationType,
  });
  const ContactLead = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeSession = IDL.Record({
    'status' : PaymentStatus,
    'bookingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'currency' : IDL.Text,
    'checkoutUrl' : IDL.Text,
    'sessionId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'adminApproveTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminDeleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminGetAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], []),
    'createConsultationCheckout' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getContactLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
    'getPaymentStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentStatus)],
        ['query'],
      ),
    'getStripeSession' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StripeSession)],
        ['query'],
      ),
    'setAdminPrincipal' : IDL.Func([IDL.Text], [], []),
    'submitBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'submitContactLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitGeneralGuidanceBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'updateStripeSession' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'verifyConsultationPayment' : IDL.Func([IDL.Text], [PaymentStatus], []),
  });
};

export const init = ({ IDL }) => { return []; };